### ISSUE TITLE
Queue Stops after 4 projects

### ISSUE THREAD

**Issue by thedurphy** [udacity/reviewer-dashboard-feedback#32] opened 2018-02-09 16:48 UTC
The queue stops after the 4th project has been assigned.  I can then add the 5th project manually but it doesn't automatically do it.

**Comment by Digizard** [comment] 2018-02-11 01:58
Possibly a duplicate of #26, though I'm not 100% sure.

**Comment by nikifi** [comment] 2018-02-11 22:17
I have this problem too

**Closed as completed** 2018-02-14 17:49 UTC

**Comment by sudhirkhanger** [comment] 2018-02-15 17:19
@amandastinesUdacity It doesn't look like this issue has been resolved. I just encountered it.

**Comment by thedurphy** [comment] 2018-02-15 19:22
@cali-step @amandastinesUdacity I just encountered this issue again.  I sent screenshot proof along with a video of having to manually assign the 5th submission.  Please open this issue again.

**Comment by nikifi** [comment] 2018-02-15 21:48
I am still encountering it too
